#!/usr/bin/env python3
import argparse
from pathlib import Path

def fmt(x: float, digits: int) -> str:
    return f"{x:.{digits}f}"

def parse_csv_floats(s: str):
    return [float(tok.strip()) for tok in s.split(",") if tok.strip()]

def parse_csv_ints(s: str):
    return [int(tok.strip()) for tok in s.split(",") if tok.strip()]

def main():
    p = argparse.ArgumentParser(
        description="Generate LaTeX critical value tables (upper-tail) for z, t, chi-square."
    )
    p.add_argument("--out", default="build/critvals.tex", help="Output .tex file path")
    p.add_argument("--alphas", default="0.10,0.05,0.025,0.01",
                   help="Comma-separated upper-tail probabilities alpha")
    p.add_argument("--df", default="",
                   help="Comma-separated df values used for t and chi-square (e.g., 19 or 24,25,26)")
    p.add_argument("--digits", type=int, default=4, help="Decimal digits for printed critical values")
    p.add_argument("--include-lower", action="store_true",
                   help="Also include LOWER-tail chi-square quantiles (i.e., chi2_{df,1-alpha})")
    args = p.parse_args()

    alphas = parse_csv_floats(args.alphas)
    dfs = parse_csv_ints(args.df) if args.df.strip() else []

    try:
        import scipy.stats as st
    except Exception as e:
        raise SystemExit(
            "Error: SciPy is required (pip/conda install scipy). "
            f"Original import error: {e}"
        )

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    alpha_cols = "c" * len(alphas)
    alpha_header = " & ".join([rf"$\alpha={a:g}$" for a in alphas])

    z_vals = [st.norm.isf(a) for a in alphas]
    z_row = " & ".join([fmt(v, args.digits) for v in z_vals])

    lines = []
    lines.append(r"% Auto-generated by make_critvals.py")
    lines.append(r"% Conventions: upper-tail critical values, i.e. q = F^{-1}(1-\alpha)")
    lines.append("")

    lines.append(r"\paragraph{Critical Values (Upper Tail)}")
    lines.append("")

    lines.append(r"\begin{center}")
    lines.append(r"\begin{tabular}{" + "l" + alpha_cols + r"}")
    lines.append(r"\hline")
    lines.append(r" & " + alpha_header + r" \\")
    lines.append(r"\hline")
    lines.append(r"$z_\alpha$ & " + z_row + r" \\")
    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{center}")
    lines.append("")

    if dfs:
        for df in dfs:
            t_vals = [st.t.isf(a, df) for a in alphas]
            t_row = " & ".join([fmt(v, args.digits) for v in t_vals])

            lines.append(r"\begin{center}")
            lines.append(r"\begin{tabular}{" + "l" + alpha_cols + r"}")
            lines.append(r"\hline")
            lines.append(rf"\multicolumn{{{1+len(alphas)}}}{{c}}{{Student $t$ critical values, df = {df}}} \\")
            lines.append(r"\hline")
            lines.append(r" & " + alpha_header + r" \\")
            lines.append(r"\hline")
            lines.append(rf"$t_{{\alpha,{df}}}$ & " + t_row + r" \\")
            lines.append(r"\hline")
            lines.append(r"\end{tabular}")
            lines.append(r"\end{center}")
            lines.append("")

        for df in dfs:
            chi_u = [st.chi2.isf(a, df) for a in alphas]
            chi_u_row = " & ".join([fmt(v, args.digits) for v in chi_u])

            if args.include_lower:
                chi_l = [st.chi2.isf(1.0 - a, df) for a in alphas]
                chi_l_row = " & ".join([fmt(v, args.digits) for v in chi_l])

                lines.append(r"\begin{center}")
                lines.append(r"\begin{tabular}{" + "l" + alpha_cols + r"}")
                lines.append(r"\hline")
                lines.append(rf"\multicolumn{{{1+len(alphas)}}}{{c}}{{Chi-square critical values, df = {df}}} \\")
                lines.append(r"\hline")
                lines.append(r" & " + alpha_header + r" \\")
                lines.append(r"\hline")
                lines.append(rf"$\chi^2_{{{df},\alpha}}$ (upper) & " + chi_u_row + r" \\")
                lines.append(rf"$\chi^2_{{{df},1-\alpha}}$ (lower) & " + chi_l_row + r" \\")
                lines.append(r"\hline")
                lines.append(r"\end{tabular}")
                lines.append(r"\end{center}")
                lines.append("")
            else:
                lines.append(r"\begin{center}")
                lines.append(r"\begin{tabular}{" + "l" + alpha_cols + r"}")
                lines.append(r"\hline")
                lines.append(rf"\multicolumn{{{1+len(alphas)}}}{{c}}{{Chi-square critical values (upper tail), df = {df}}} \\")
                lines.append(r"\hline")
                lines.append(r" & " + alpha_header + r" \\")
                lines.append(r"\hline")
                lines.append(rf"$\chi^2_{{{df},\alpha}}$ & " + chi_u_row + r" \\")
                lines.append(r"\hline")
                lines.append(r"\end{tabular}")
                lines.append(r"\end{center}")
                lines.append("")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path}")

if __name__ == "__main__":
    main()